[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[fmt] # See https://book.getfoundry.sh/reference/config/formatter
int_types = "short"
line_length = 120
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "single"
ignore = ['./script/**/*']